### ISSUE TITLE
Force close 

### ISSUE THREAD

**Issue by viruz82** [Mastaaa1987/vavoo-parser#3]
Moin. Ich habe die 1.3.2_arm64-v8a auf meinem Samsung Galaxy S23 Ultra installiert. Die App startet, fragt nach der Berechtigung für Benachrichtigung und schließt sich direkt wieder. Es hilft auch nicht, wenn ich der App alle Berechtigungen gebe.

**Comment by viruz82** [comment]
![Screenshot_20230729_001658_Permission controller](https://github.com/Mastaaa1987/vavoo-parser/assets/19948134/08d1d415-21c0-4386-8ce2-5f0fadec4bd9)

**Comment by Mastaaa1987** [comment]
Guck Ma lieber meinen neuen branch an das zwar nur cli Version aber mit Menü und xstream Plugin für vods & Serien von allen stream Sites wo geht ;-) xstream branch

**Comment by Mastaaa1987** [comment]
Achja irgendwann kommt auch neue App Version, hab schon 70% neu gemacht dass TV Oberfläche mit integriert ist dann kannste direkt von TV nutzen

**Comment by viruz82** [comment]
@Mastaaa1987 klingt interessant. Aber wo finde ich den neuen Branch? 🤔

Klingt gut mit der App. Bin gespannt.

**Comment by Mastaaa1987** [comment]
GitHub.com/Mastaaa1987/vavoo-parser/trees/xstream

**Comment by Mastaaa1987** [comment]
https://github.com/Mastaaa1987/vavoo-parser/tree/xstream

**Comment by viruz82** [comment]
Danke dir! Hab ich aufm Handy nicht gefunden. 🙄 🙈

**Comment by Mastaaa1987** [comment]
Jaja glaub mir wie lange hab ich jetzt versucht mit handy xstream branch als main branch zu marken...
Musste jetzt schlussendlich doch lappi nehmen um das machen zu können kp :-D

**Comment by viruz82** [comment]
Haha, das glaub ich dir. :D 

Hab jetzt deinen neuen Branch installiert. Super cool! 👍 Hab da aber auch ein Problem, ich mach mal nen neuen Case dazu auf.
