### ISSUE TITLE
Server is shut down.

### ISSUE THREAD

**Issue by digitvadmin** [Mastaaa1987/vavoo-parser#4]
Please fix it ?

**Comment by Mastaaa1987** [comment]
What do you mean?

**Comment by Mastaaa1987** [comment]
> Please fix it ?

Check Out my New branch ... 
ITS cli only but nice Menü & in mass vods & series on all Public Stream Sites ;-)

**Comment by digitvadmin** [comment]
> > Please fix it ?
> 
> Check Out my New branch ... 
> ITS cli only but nice Menü & in mass vods & series on all Public Stream Sites ;-)

Where ? Please link.
