### ISSUE TITLE
Fehler beim Hinzufügen eines Films

### ISSUE THREAD

**Issue by viruz82** [Mastaaa1987/vavoo-parser#5]
Ich wollte Fast & Furious 10 (cinemathek) hinzufügen und bekomme einen Fehler. Kann das am Sonderzeichen, also dem Und-Zeichen liegen?

```
Traceback (most recent call last):
  File "/opt/vavoo-parser/main.py", line 13, in <module>
    main()
  File "/opt/vavoo-parser/main.py", line 9, in main
    cli.menu()
  File "/opt/vavoo-parser/cli.py", line 156, in menu
    ser = xstream.search(quest['item'])
  File "/opt/vavoo-parser/utils/xstream.py", line 353, in search
    if not entry['key'] == 'showHosters':
KeyError: 'key'
```

**Comment by Mastaaa1987** [comment]
Ne das glaubig eher cinemathek Seite, aber werde morgen Mal schauen genau los ist... Gibt's denn Film nicht auf anderen Sites?

**Comment by Mastaaa1987** [comment]
Ist auf jedenfallv nen Problem in der Suche, ich fix das Weg wenn ich xtream API Update, Programm Code dafür steht schon fast, sollte also nicht mehr all zu lange dauern ;-)

**Comment by viruz82** [comment]
Zu welchen Zeiten bist du denn wach? 😄
Alles klar, danke dir! 😊

**Comment by Mastaaa1987** [comment]
Ich? Immer natürlich ^^

**Comment by Mastaaa1987** [comment]
kann ich aber closen wa?
